#!/bin/bash

# AUTHOR:   (c) Rob W 2012, modified by MHC (http://askubuntu.com/users/81372/mhc)
# NAME:     GIFRecord 0.1
# DESCRIPTION:  A script to record GIF screencasts.
# LICENSE:  GNU GPL v3 (http://www.gnu.org/licenses/gpl.html)
# DEPENDENCIES:   byzanz,gdialog,notify-send (install via sudo add-apt-repository ppa:fossfreedom/byzanz; sudo apt-get update &;&; sudo apt-get install byzanz gdialog notify-osd)

set -e

# Time and date
TIME=$(date +"%Y-%m-%d_%H%M%S")

# Delay before starting
DELAY=1

# Standard screencast folder
FOLDER="$HOME/Pictures"

# Default recording duration
DEFDUR=60

# Sound notification to let one know when recording is about to start (and ends)
beep() {
    paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga &
}

if [ "$1" = "--help" ]
then
	echo "Usage : "
	echo "byzanz-gui <duration> <delay>"
	exit 0
fi
# Custom recording duration as set by user
USERDUR="${1:-$DEFDUR}"
DELAY="${2:-$DELAY}"
# Duration and output file
if [ "$USERDUR" -gt 0 ]; then
    D="$USERDUR"
else
    D="$DEFDUR"
fi
echo "recording for $D seconds"

# Window geometry
echo "please select the window you want to record"
XWININFO=$(xwininfo)
read X < <(awk -F: '/Absolute upper-left X/{print $2}' <<< "$XWININFO")
read Y < <(awk -F: '/Absolute upper-left Y/{print $2}' <<< "$XWININFO")
read W < <(awk -F: '/Width/{print $2}' <<< "$XWININFO")
read H < <(awk -F: '/Height/{print $2}' <<< "$XWININFO")

# #Actual recording
sleep "$DELAY"

#b "#FFFFFF" "start recording" || true
byzanz-record -c --verbose --delay=0 --duration=$D --x="$X" --y="$Y" --width="$W" --height="$H" "$FOLDER/GIFrecord_$TIME.gif"
beep

# Notify the user of end of recording.
notify-send "GIFRecorder" "Screencast saved to $FOLDER/GIFrecord_$TIME.gif"
#b "#FFFFFF" "stopped recording" || true
